# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5a35a00d6bc4219567f2b7745601bfb7503a8ae18d835787c58e487d67fadc3a962c3cfd7bd12bddb99e4f71e39f8501907675c26cc84808160b903bdb133768

test:
  secret_key_base: 5da1c0862e9c0f6e0bf43b06e6eb8ecdfd6a8be0e92e3b6d1d94b4f33678e77cffda2f4237decabbbe3127071447eab2379945cf3aba41095230300638f1ea2d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
